### ISSUE TITLE
dsda-doom M1 Mac build

### ISSUE THREAD

**Issue by Pedro-Beirao** [atsb/source-port-builds#1]
The M1 build of dsda-doom is broken.

The launcher says: "Launcher.app" is damaged and cant be opened
The actual dsda-doom is not a static build and does not provide the required dynamic libraries

The Intel version's Launcher does open, but the dsda-doom executable has the same problem.

Im making a crossplatform Launcher for this source port, which also packs dsda-doom with the required dynamic libraries.
You might like to take a look.
It includes binaries for both MacOS universal and Windows, but only MacOS is stable, for now
https://github.com/Pedro-Beirao/dsda-launcher

**Comment by atsb** [comment]
Thanks!  I think I know the reason.  I'll get that fixed pronto!  I like your link, it looks great.  If that's what you'll provide then it is great to have another place to get Mac builds with a decent launcher.  I never liked the prboom launcher at all.
